# Generated by Django 2.2.12 on 2020-07-01 20:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import stream_django.activity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('funding_goal', models.IntegerField()),
                ('total_raised', models.IntegerField(default=0)),
                ('info', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('goals_finished', models.BooleanField(default=False)),
                ('funding_finished', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-round_number'],
                'get_latest_by': 'created_at',
            },
            bases=(models.Model, stream_django.activity.Activity),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('info', models.TextField(unique=True)),
                ('city', models.CharField(max_length=20)),
                ('intro_video', models.FileField(upload_to='videos')),
                ('photo', models.ImageField(upload_to='photos')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('seeking_funding', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Country')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Entrepreneur')),
                ('looking_for', models.ManyToManyField(to='projects.Collaborator')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
            bases=(models.Model, stream_django.activity.Activity),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('accomplished', models.BooleanField(default=False)),
                ('funding_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.FundingRound')),
            ],
        ),
        migrations.AddField(
            model_name='fundinground',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='fundinground',
            unique_together={('round_number', 'project')},
        ),
    ]
