# Generated by Django 2.2.12 on 2020-07-01 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('ipn_sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paypal_invoice', models.CharField(max_length=19, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('funding_round', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FailedPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_id', models.TextField(blank=True, null=True)),
                ('ipn_sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paypal_invoice', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('error_manually_reviewed', models.BooleanField(default=False)),
                ('currency', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('funding_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_amount', models.IntegerField()),
                ('new_amount', models.IntegerField()),
                ('change', models.IntegerField()),
                ('description', models.TextField(blank=True, default='A payment has been reversed from PayPal, this has been recorded on the contributions page as a new negative amount contribution. No further action required unless contribution_not_found is equal to True. This should in theory never happen but if it does, contact faisal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution_not_found', models.BooleanField(default=False)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contribute.Contribution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_id', models.TextField(blank=True, null=True)),
                ('ipn_sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paypal_invoice', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('error_manually_handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contribute.Contribution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contribute.Pledge'),
        ),
    ]
