# Generated by Django 2.2.12 on 2020-07-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FailedPayment',
            new_name='NonCompletePayment',
        ),
        migrations.AddField(
            model_name='contribution',
            name='amount_final',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='funding_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
    ]
