# Generated by Django 2.2.12 on 2020-07-06 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('contribute', '0002_auto_20200705_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'time',
            },
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='amount',
        ),
        migrations.AddField(
            model_name='contribution',
            name='amount_after_paypal_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contribution',
            name='amount_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contribution',
            name='gh_fee_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='funding_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.FundingRound'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
